export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE'


export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const ADD_PRODUCT = 'ADD_PRODUCT'